### ISSUE TITLE
EGM08EarthAccel acceleration conversion from ITRS to GCRS

### ISSUE THREAD

**Issue by akn264** [USNavalResearchLaboratory/TrackerComponentLibrary#13]
Does the ITRS2GCRS conversion for accel in line 348 need more calculations? In the comments it says that the ITRS2GCRS function takes in either position vector or both position and velocity vectors. Is it still valid to just use that function for converting the acceleration? Thank you!

**Comment by DavidFCrouse** [comment]
The ITRS and the GCRS coordinate systems share the same origin. Thus, the call to ITRS2GCRS just rotates the vector to the correct orientation. The acceleration returned in the ITRS is more of an approximation, because it doesn't include things like the derivatives of the celestial pole motion location, which represent the change of the orientation of the ITRS with respect to the GCRS over time.
